
apiVersion: v1
kind: ConfigMap
metadata:
  name: chatapp-conf
data:
  nginxconf.conf: |
                  server{
                  listen 80;
                  location / {
                  proxy_pass http://backend-service:8000;
                   }
                  }
